baseurl = "https://andrewwohlfeil.com/"
languageCode = "en-us"
title = "Andrew Wohlfeil's Personal Website"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
  name = "Home"
  url = "/about"
  weight = 1
[[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = 6    

#[[menu.main]]
#    name = "GitHub"
#    url = "https://github.com/wohlfeila/"
#[[menu.main]]
#    name = "Twitter"
#    url = "https://twitter.com/AndrewWohlfeil/"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"
    
    author = "Andrew Wohlfeil"
    date_format = "Mon, Jan 2, 2006"

    [params.logo]
    # main logo top right corner
    url = "aw_logo.png"
    width = 50
    height = 50
    alt = "Logo"

[[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/wohlfeila"
    
[[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/AndrewWohlfeil"    

[[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "//www.linkedin.com/in/andrew-wohlfeil-441b6591/"    